# Generated by Django 3.1.3 on 2021-07-19 16:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoneNumber', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
        ),
        migrations.AddField(
            model_name='user_details',
            name='Branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ICT', 'ICT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('EIE', 'EIE'), ('Mechanical', 'Mechanical'), ('Mechatronics', 'Mechatronics'), ('Civil', 'Civil'), ('Bio-Technology', 'Bio-Technology')], max_length=254),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Id_card_pic',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Mobile_no',
            field=models.CharField(blank=True, max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Password',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Sastra_email_id',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='user_details',
            name='Status',
            field=models.CharField(default='Not-Verified', max_length=254),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Name',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Register_no',
            field=models.CharField(blank=True, max_length=9, unique=True),
        ),
    ]
