# Generated by Django 3.1.3 on 2021-07-19 16:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_app', '0003_auto_20210719_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Branch',
            field=models.CharField(choices=[('CSE', 'CSE'), ('IT', 'IT'), ('ICT', 'ICT'), ('ECE', 'ECE'), ('EEE', 'EEE'), ('EIE', 'EIE'), ('Mechanical', 'Mechanical'), ('Mechatronics', 'Mechatronics'), ('Civil', 'Civil'), ('Bio-Technology', 'Bio-Technology')], max_length=254),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Id_card_pic',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Mobile_no',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')]),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Name',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Password',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Register_no',
            field=models.CharField(max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name='user_details',
            name='Sastra_email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
