# Generated by Django 3.1.3 on 2021-07-19 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_app', '0004_auto_20210719_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='Status',
            field=models.CharField(choices=[('Verified', 'Verified'), ('Not-Verified', 'Not-Verified')], default='Not-Verified', max_length=254),
        ),
    ]
