# Generated by Django 3.1.3 on 2021-07-20 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missing_app', '0005_auto_20210719_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
