# Generated by Django 3.1.3 on 2021-07-31 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_app', '0010_auto_20210730_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='items_lost',
            name='catogeory',
            field=models.CharField(default='Lost', max_length=50),
        ),
        migrations.AddField(
            model_name='items_lost',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 31, 8, 19, 48, 105170)),
        ),
    ]
