# Generated by Django 3.1.3 on 2021-08-01 04:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('missing_app', '0012_auto_20210801_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_lost',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 8, 1, 10, 26, 23, 778535)),
        ),
        migrations.CreateModel(
            name='Contact_us',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
