# Generated by Django 3.1.3 on 2021-08-01 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_app', '0019_auto_20210801_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items_lost',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
